backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: '/public/posts'
collections:
  - name: 'posts'
    label: 'Posts'
    folder: '/src/pages/posts'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
