backend:
  name: git-gateway
  branch: main
media_folder: '/public/posts'
collections:
  - name: 'posts'
    label: 'Post'
    folder: '/src/pages/posts'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: '../../layouts/MarkdownPostLayout.astro',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Publish Date',
          name: 'pubDate',
          widget: 'datetime',
          date_format: 'MM-DD-YYYY',
          format: 'YYYY-MM-DD',
          time_format: false,
        }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'hidden', default: 'Christina' }
      - { label: 'Featured Image', name: 'image_url', widget: 'image' }
      - { label: 'Featured Image Label', name: 'image_alt', widget: 'string' }
      - {
          label: 'Categories',
          name: 'tags',
          widget: 'select',
          multiple: true,
          min: 1,
          options: ['Birthdays', 'Christmas', 'Valentines', 'Scriptures'],
          default: ['Scriptures'],
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
